name: PR Build Check

on:
  pull_request:
    branches:
      - "develop"
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 체크아웃
        uses: actions/checkout@v4

      - name: Node.js 설치
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: 의존성 설치
        run: npm ci

      - name: 타입 체크
        run: npx tsc --noEmit

      - name: 빌드
        run: npm run build
